Problem 1

In [8]:
import numpy as np

empty_array = np.empty((2, 2))
print("1. Empty Array 2x2:\n", empty_array)

ones_array = np.ones((4, 2))
print("\n2. Ones Array 4x2:\n", ones_array)

filled_array = np.full((2, 3), 7)
print("\n3. Filled Array 2x3 with 7:\n", filled_array)

shape_of_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like = np.zeros_like(shape_of_array)
print("\n4. Zeros Like Array:\n", zeros_like)

ones_like = np.ones_like(shape_of_array)
print("\n5. Ones Like Array:\n", ones_like)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\n6. Array from List:\n", array_from_list)


1. Empty Array 2x2:
 [[1.14e-322 2.52e-322]
 [6.42e-323 1.43e-322]]

2. Ones Array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled Array 2x3 with 7:
 [[7 7 7]
 [7 7 7]]

4. Zeros Like Array:
 [[0 0 0]
 [0 0 0]]

5. Ones Like Array:
 [[1 1 1]
 [1 1 1]]

6. Array from List:
 [1 2 3 4]


Problem 2

In [9]:
range_array = np.arange(10, 50)
print("\n1. Array with values ranging from 10 to 49:\n", range_array)

matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix with values ranging from 0 to 8:\n", matrix_3x3)

identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_random_array = random_array.mean()
print("\n4. Mean of Random Array of size 30:", mean_random_array)

random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n5. Min and Max of 10x10 Random Array:\nMin:", min_val, " Max:", max_val)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero Array with 5th element replaced by 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 on Border and 0 Inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)



1. Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of Random Array of size 30: 0.5166541317556136

5. Min and Max of 10x10 Random Array:
Min: 0.004858133336815396  Max: 0.9994685081174653

6. Zero Array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0 4 0 0 2 1]

8. 2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3

In [10]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

array_add = np.add(x, y)
print("\n1. x + y:\n", array_add)

array_subtract = np.subtract(x, y)
print("\n2. x - y:\n", array_subtract)

array_multiply = x * 2
print("\n3. x multiplied by 2:\n", array_multiply)

array_square = np.power(x, 2)
print("\n4. Square of each element in x:\n", array_square)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot Product (v . w, x . v, x . y):", dot_vw, dot_xv, dot_xy)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("\n6. Concatenate x and y along row:\n", concat_xy_row)
print("\nConcatenate v and w along column:\n", concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=1)
except ValueError as e:
    print("\n7. Error when concatenating x and v:", e)



1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x multiplied by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot Product (v . w, x . v, x . y): 219 [29 77] [[19 22]
 [50 58]]

6. Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column:
 [[ 9 11]
 [10 12]]

7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4

In [11]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A * A^-1 = Identity Matrix:\n", identity)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. Prove AB ≠ BA:\nAB:\n", AB, "\nBA:\n", BA)

transpose_AB = np.transpose(AB)
transpose_BA = np.dot(np.transpose(B), np.transpose(A))
print("\n3. Prove (AB)^T = B^T * A^T:\n(AB)^T:\n", transpose_AB, "\nB^T * A^T:\n", transpose_BA)

A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

X = np.linalg.solve(A_matrix, B_matrix)
print("\nLinear Equation Solution (x, y, z):", X)


1. A * A^-1 = Identity Matrix:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Prove AB ≠ BA:
AB:
 [[23 13]
 [51 29]] 
BA:
 [[36 44]
 [13 16]]

3. Prove (AB)^T = B^T * A^T:
(AB)^T:
 [[23 51]
 [13 29]] 
B^T * A^T:
 [[23 51]
 [13 29]]

Linear Equation Solution (x, y, z): [ 2.  1. -2.]
